components:
  # Компоненты верхнего уровня (L1 C4Model)
  test_department.user:                       # Идентификатор компонента
    title: Пользователь       # Название
    entity: actor             # Представление на схеме
    links:                    # Компоненты, с которыми происходит взаимодействие
      - id: test_domen.system1            # Идентификатор компонента
        direction: <-->       # Направление взаимодействия (<-- | -- | --> | <-->)
        title: Покупка        # Смысл взаимодействия