aspects:
  auth:                       # Идентификатор аспекта
    title: Авторизация         # Название
    location: Авторизация     # Размещение в меню
  goods:
    title: Покупка товара
    location: Покупка товара
  goods.order:                # Структурированные идентификаторы аспектов определяют их иерархию
    title: Заказ товара
    location: Покупка товара/Заказ
  goods.payment:
    title: Оплата товара
    location: Покупка товара/Оплата
